### ISSUE TITLE
Null pointer exception when sample usage testing

### ISSUE THREAD

**Issue by laki88** [idealista/format-preserving-encryption-java#7]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

I got a null pointer exception when sample usage testing

### Steps to Reproduce

1. Add this project library to maven dependency
2. Ran the below code
// with default values
        FormatPreservingEncryption formatPreservingEncryption = FormatPreservingEncryptionBuilder
                .ff1Implementation()
                .withDefaultDomain()
                .withDefaultPseudoRandomFunction("laki".getBytes())
                .withDefaultLengthRange()
                .build();

//usage
        String cipherText = formatPreservingEncryption.encrypt("12121", "mytweak".getBytes());
        String plainText = formatPreservingEncryption.decrypt(cipherText, "mytweak".getBytes());

        System.out.println(cipherText);
        System.out.println(plainText);

**Expected behavior:**
Should print cipher text and plain text
**Actual behavior:** 

got a null pointer exception

Exception in thread "main" java.lang.NullPointerException
	at com.idealista.fpe.config.GenericTransformations.transform(GenericTransformations.java:37)
	at com.idealista.fpe.config.GenericDomain.transform(GenericDomain.java:25)
	at com.idealista.fpe.FormatPreservingEncryption.encrypt(FormatPreservingEncryption.java:28)
	at experiment.EncryptionTest.main(EncryptionTest.java:81)

**Reproduces how often:**
100%

### Versions

1.0.0

**Comment by laki88** [comment]
The problem is it can't encrypt a number sequence. when I use letters in alphabet for the input stream I can encrypt and decrypt it without any issue.

**Comment by meghnad-globalids** [comment]
I am also facing the same issue, any updates on this?

**Comment by laki88** [comment]
To solve that, I have created below class and added to classpath

```
package com.wso2telco.dep.user.masking;

import com.idealista.fpe.config.Alphabet;

public class BasicNums implements Alphabet {

    private static final char[] NUM_CHARS = new char[] {'1', '2', '3', '4', '5', '6', '7', '8', '9' , '0'};

    @Override
    public char[] availableCharacters() {
        return NUM_CHARS ;
    }

    @Override
    public Integer radix() {
        return NUM_CHARS.length;
    }
}
```

and used it as in below code

```
BasicNums numAlphabet = new BasicNums();
        TextToIntTransformer textToIntTransformer = new GenericTransformations(numAlphabet.availableCharacters());
        IntToTextTransformer intToTextTransformer = new GenericTransformations(numAlphabet.availableCharacters());

        // with default values
        FormatPreservingEncryption formatPreservingEncryption = FormatPreservingEncryptionBuilder
                .ff1Implementation()
                .withDomain(new GenericDomain(new BasicNums(), textToIntTransformer, intToTextTransformer))
                .withDefaultPseudoRandomFunction(secretKey.getBytes())
                .withDefaultLengthRange()
                .build();
```

**Comment by meghnad-globalids** [comment]
Will be possible for this encryption tool to encrypt character wise based on domain, as in my case the 
 string might be alphanumeric?

**Comment by lijhua** [comment]
I also encountered this problem in the beginning, and solved it in the following way.
1, if the content to be encrypted contains only numbers, then construct NUM_CHARS like this
 private static final char[] NUM_CHARS = new char[] {'1', '2', '3', '4', '5', '6', '7', '8', '9' , '0'}；
2, if the content to be encrypted contains numbers and uppercase letters, then construct NUM_CHARS
private static final char[] NUM_CHARS = new char[] {'1', '2', '3', '4', '5', '6', '7', '8','9','0','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'};
3, other situations are changed with steps 1 and 2

then

  BasicNums numAlphabet=new BasicNums();
        TextToIntTransformer textToIntTransformer = new GenericTransformations(numAlphabet.availableCharacters());
        IntToTextTransformer intToTextTransformer = new GenericTransformations(numAlphabet.availableCharacters());
        String secretKey = "privateKeyText";
        // with default values
        FormatPreservingEncryption formatPreservingEncryption = FormatPreservingEncryptionBuilder
            .ff1Implementation()
            .withDomain(new GenericDomain(new BasicNums(), textToIntTransformer, intToTextTransformer))
            .withDefaultPseudoRandomFunction(secretKey.getBytes())
            .withDefaultLengthRange()
            .build();

        String cipherText = formatPreservingEncryption.encrypt("1212321ASDSAD", "2088".getBytes());
        System.out.println(cipherText);
        String plainText = formatPreservingEncryption.decrypt(cipherText, "2088".getBytes());
        System.out.println(plainText);

output:
WU69RQ3AB5IRR
1212321ASDSAD
